name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:
    secrets:
      codecov_token:
        required: true

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/detect-jdk
      - &setup_jdk
        name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
          cache: maven
      - name: Install OpenBLAS on Linux
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev
      - name: Build with Maven
        run: mvn -B clean verify -P coverage --file pom.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.codecov_token }}
          slug: atraplet/highs4j

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/detect-jdk
      - *setup_jdk
      - name: Install OpenBLAS on Windows
        shell: bash
        run: |
          vcpkg install openblas[threads]
      - name: Add vcpkg bin to PATH
        shell: bash
        run: |
          echo "$VCPKG_INSTALLATION_ROOT/installed/x64-windows/bin" >> $GITHUB_PATH
      - &build_with_maven
        name: Build with Maven
        run: mvn -B clean verify --file pom.xml

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/detect-jdk
      - *setup_jdk
      - *build_with_maven
